"""3. The Fibonacci sequence is a famous sequence in mathematics where each term is generated by adding the two previous terms: 0,1,1,2,3,5,8,13,21,34,55,...Using a while loop, write a function that would find the nth Fibonacci number. For example, the 4th number would be 2 and the 6th number would be 5.
"""
def nth_fibo(n):
    total, fib, ne, k = 0, 0, 1, 1
    while k < n:
        total = fib + ne
        fib = ne
        ne = total
        k = k + 1
    return fib

# Better way
def nth_fibo1(n):
    count, curr, next = 1, 0, 1
    while count < n:
        curr, next = next, curr + next
        count = count + 1
    return curr

print(nth_fibo(6))
print(nth_fibo(10))
print(nth_fibo1(6))
print(nth_fibo1(10))
